import Head from "next/head";
import Navbar from "./components/Navbar";
import Posts from "./components/Posts/Posts";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Liner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Posts />
    </div>
  );
}
